### ISSUE TITLE
genes resources.py raises error when genes have empty synonyms

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#247]
The issue is here
0069e45d
line 31 and 32. The synonym model has no attribute "name". 
Either way, when a gene is created with an empty synonym (which is not a required argument), this resource call fails.

**Comment by naegelyd** [comment]
I assume by line 31-32 you are referring to [these lines](https://github.com/cbmi/varify/blob/master/varify/genes/resources.py#L31-L32), right? Assuming that is the case, I am not sure about this issue. Those lines are not referencing the `name` attribute of a synonym. They are accessing `data['name']` where data is the serialized gene data as generated by [this line](https://github.com/cbmi/varify/blob/master/varify/genes/resources.py#L28).

As to the second point, the `synonym` field on a `Gene` model is a `ManyToManyField` which, be default, means a gene can be created without _any_ synonyms existing. [By definition](https://github.com/cbmi/varify/blob/master/varify/genes/models.py#L49-L56), the gene can have 0 or more `articles`, `synonyms`, and `phenotypes`. 

Based on the above, I am not sure what this issue is reporting. Please add some clarification and steps to recreate so we can categorize this issue.

**Comment by naegelyd** [comment]
The issue was identified to be that [these lines](https://github.com/cbmi/varify/blob/master/varify/genes/resources.py#L31-L32) have no guarantee that the `name` and/or `symbol` are in the `data['synonyms']` list so the remove will fail if `name` or `symbol` are not in the list.
