### ISSUE TITLE
Exclude null values when filtering using range control

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#282]
Not sure if this is a Cilantro issue or a Varify one but I will start here and we can move it later if need by. Today I encountered this case. There was a sample with `297.8K` results.   Here are the filter sets and the result counts. Let's say the total when filtering 1000g <= 0.5 is `A` and the total when filtering when 1000g >= 0.5 is `B`. I would fully expect that `A+B = 297.8K`, roughly since there might be overlap at exactly `0.5`. I do _not_ expect this overlap to be nearly `100K` results as it would appear below. When filtering for values <= 0.5 or values >= 0.5 I see results that have no 1000g frequencies which means some results(about `100K` by my estimates in this case) are being included not matter what is supplied in the range because they have null values for 1000g. I believe that null values should be excluded when a range is supplied because the user is explicitly asking for results that occur within some range which means they _must_ have a value in that range which null never truly satisfies. I suppose I could be convinced that nulls should always be treated as 0.0 or infinity but I think they should just be discarded completely in cases like this.

![screen shot 2014-04-30 at 1 55 34 pm](https://cloud.githubusercontent.com/assets/3911912/2844961/05b38480-d091-11e3-877c-7071ed960611.png)
![screen shot 2014-04-30 at 1 56 25 pm](https://cloud.githubusercontent.com/assets/3911912/2844963/05b430a6-d091-11e3-8aa2-bf82e88a7930.png)
![screen shot 2014-04-30 at 1 55 40 pm](https://cloud.githubusercontent.com/assets/3911912/2844962/05b3e7cc-d091-11e3-8d21-397a6b835565.png)

**Comment by mitalia** [comment]
This is is the expected behavior in this case. Users don't want variants thrown out simply because they have a 1000 genomes filter in place and the variant is not in 1000 genomes. These are the variants most likely to be disease causing. The likely optimal solution is to be more transparent about what is happening under the hood by showing "1000 genomes frequency is less than X or is absent".

**Comment by naegelyd** [comment]
I understand that people need to see the null cases but we currently treat null values as both 0 and infinity which, in my opinion, is highly confusing. I have no strong opinion on how we handle nulls aside from the fact that I don't believe we can keep including them in _all_ queries. For example, we cannot consider null to be both less than 0.5 AND greater than 0.5 like is occurring above because no matter what explanation we include, it will still be confusing if we include nulls in all cases.

**Comment by mitalia** [comment]
Ah I missed the detail that we were including at both ends. That most definitely does not make sense. Nulls are equivalent to zero in this specific instance, not infinity. The 1000 genomes allele frequencies are the frequency of occurrence of variants in the 1000 genomes population. So an absence of a variant in the table is effectively zero. A value of infinity makes no sense, because that would imply that everyone in 1000 genomes has the variant, which is false.

**Comment by naegelyd** [comment]
Users are reporting this is an issue again. Now, it seems nulls are not being included at all. For example, a given sample has 171.2K results. Setting 1000g to filter >= 0.05 gets 129.5K results. Changing it to 1000g <= gets us 7.7K. Checking the null count from the shell we see that there are 35.1K null values so we can see that nulls are not being considered in any case.

**Comment by naegelyd** [comment]
To resolve this issue, the `varify.variants` needs to be added to installed apps and an empty migrations folder will need to be added so that south will not freak out. Additionally, `manage.py avocado migration` should be run after modifying all the 1000g and EVS fields so that new installations will be using the translator by default.

**Comment by naegelyd** [comment]
This was just an issue with the translators becoming unassigned.
