### ISSUE TITLE
annotate.py management subcommand not registered in variants.py

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/varify#301]
Should https://github.com/cbmi/varify/blob/master/varify/variants/management/subcommands/annotate.py be registered in https://github.com/cbmi/varify/blob/master/varify/variants/management/commands/variants.py?

**Comment by naegelyd** [comment]
This command was never registered in the internal version(before public release here) so I am guessing it should remain unregistered. 

@bruth do you know if we need the `annotate` or the `md5` commands(located [here](https://github.com/cbmi/varify/tree/master/varify/variants/management/subcommands)) any more? They aren't registered which leads me to suspect they are no longer used. If they are still necessary, I will add notes to each indicating they are for internal use only and they are intentionally left unregistered. Otherwise, I will delete them altogether.

**Comment by bruth** [comment]
They are no longer needed.
