### ISSUE TITLE
Idea: Clear filter from text box when removed from filter panel 

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#304]
![screen shot 2014-05-21 at 9 50 06 am](https://cloud.githubusercontent.com/assets/2774472/3040849/15217cf6-e0ef-11e3-800a-353815c18f7c.png)

As of now, when I do not want a filter and I remove it from the filters panel, the filter still stays in the text box. 
For the convenience of the user, it might be useful to remove this filter also from the text box when they remove it from the filter panel.

Just an idea

**Comment by bruth** [comment]
Definitely a valid idea, however I personally tend to grumble when an application removes my hand-entered input. Since these two parts are decoupled, I do not see value in clearing the input, but I could see a user complaining because they didn't expect it.

**Comment by naegelyd** [comment]
Ha, I made a similar request a while back [with the infograph control](https://github.com/cbmi/cilantro/issues/178). I originally assumed that removing the filter would reset the control. However, I think the current behavior is the right way to do it. The context panel simply represents the applied filters. The controls are your working copy. Clearing an applied filter should not(and does not currently) affect your working state which is why it behaves the way it does now. For example, what if you applied a filter, made some changes in the control but didn't click update, then removed the filter. Would you reset the control or leave the control as is because it is modified? I think the current behavior is the best and that users will quickly learn what to expect. Also, the more complex controls have internal clear all buttons and there are issue(s) to add clear buttons to text boxes so it is/will be easy enough for the user to clear the control themselves.

@hassanNS @bruth Unless there is a strong case for the clear on remove behavior, I'll go ahead and close this.

**Comment by hassanNS** [comment]
Hmm now that you guys made the case it makes sense. We could certainly add this option in as a setting into cilantro but if it isn't really useful and becomes a hindrance at some point as @naegelyd mentioned, then I don't see a use. Thanks for the feedback
