### ISSUE TITLE
Genomic position should allow SI prefixes

### ISSUE THREAD

**Issue by leipzig** [chop-dbhi/varify#324]
It's too hard to keep track of zeros when typing in these ranges.

![screen shot 2014-06-12 at 1 15 10 pm](https://cloud.githubusercontent.com/assets/147991/3261105/58a15b96-f255-11e3-9128-dedb28c91163.png)

**Comment by naegelyd** [comment]
These fields support scientific notation. So, you could write this as:

![screen shot 2014-07-01 at 1 27 35 pm](https://cloud.githubusercontent.com/assets/3911912/3446686/df301dac-0144-11e4-96a8-8246ff29ebfc.png)

which would result in the desired filter of

![screen shot 2014-07-01 at 1 27 39 pm](https://cloud.githubusercontent.com/assets/3911912/3446690/e66a16d6-0144-11e4-8667-35c2b6126ce9.png)

@leipzig Unless there is an absolute need for support for SI suffixes, the method shown in the image above using scientific notation should suffice and we can close this. This will also become clearer once cbmi/cilantro#529 is implemented so that as the user types, the filter text will be shown and in the case of large numbers, they will be delimited making them clear even with long sequences of zeroes.

**Comment by leipzig** [comment]
ok, maybe a tooltip since most geneticists will not remember 150M is 1.5e8
