### ISSUE TITLE
Add genome version to sample and variant resources

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/varify#389]
This ensures consumers (see https://github.com/cbmi/varify/pull/384#issuecomment-58953721) are aware of the genome version the samples and variants are referenced to.

This depends on cbmi/varify-data-warehouse#23

**Comment by naegelyd** [comment]
@bruth Given our modified approach for cbmi/varify-data-warehouse#23 is this still relevant? Since we didn't add this field to either the sample or variant model, I'm wondering where this data should be made available. From my perspective, we could either add a /genome/ endpoint that returns the required version(if any exists) from the settings or we could embed this data in the returned info from /samples/ and /variants/ resources. Thoughts?

**Comment by bruth** [comment]
All three endpoints (`/samples/`, `/variants`, `/genome>/`) would benefit from including the version number, mainly because it is a static value so there is no overhead and to prevent needing to hit `/genome/` separately.

That being said, the fact that cbmi/varify-data-warehouse#23 made setting the `VDW_REQUIRED_GENOME_VERSION` optional makes this static value no longer useful. I think we need to change VDW to require the `VDW_GENOME_VERSION` (name change) to be set since we are assuming everywhere else that samples cannot be loaded that differ in the genome version used.

**Comment by naegelyd** [comment]
Depends on cbmi/varify-data-warehouse#35.
