### ISSUE TITLE
Stats model required.

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#396]
Steps to recreate:
1) install the latest cilantro commit on varify
2) login
3) go to the console and see
![error](https://cloud.githubusercontent.com/assets/2774472/4681892/0fdb75e2-5617-11e4-9232-6d7aa104ed31.png)

**Comment by naegelyd** [comment]
Varify does not currently officially support the latest version of Cilantro(we are still on 2.3.5) because of this change and others in areas that Varify overrides. The move to Cilantro 2.3.6 will require some updates in Varify. I'm going to close this since this work will be done when Cilantro 2.3.6(or a newer version) is embedded in Varify.

**Comment by hassanNS** [comment]
@naegelyd I'm trying https://github.com/cbmi/cilantro/issues/529
Is there a way I can test my changes to cilantro? Openmrs has only date controls.
If I use an earlier commit of cilantro then merging it w/ the latest commits might be a problem?

Thanks

**Comment by naegelyd** [comment]
@hassanNS I am doing a Cilantro release now and then I will update Varify with that new version. That should solve your problems.

**Comment by naegelyd** [comment]
@hassanNS Or, if you need it right away, you can add this `stats: this.data.stats` under [this line](https://github.com/cbmi/cilantro/blob/b65cfed0c06099e95d0bed2d919cfb6025dddd2b/src/js/cilantro/main.js#L123) and you should be OK after that.

**Comment by naegelyd** [comment]
@hassanNS beb45f0170c7c572cfbb803 updates Varify to use Cilantro 2.3.6.

**Comment by hassanNS** [comment]
Thanks!
